(library
 (name reviewotron_lib)
 (libraries
  atdgen-runtime
  base64
  containers
  curl
  devkit
  devkit.core
  extlib
  digestif
  lwt
  lwt.unix
  melange-json-native
  unix
  mirage-crypto-pk
  ppx_deriving_jsonschema.runtime
  ptime
  ptime.clock.os
  re2
  x509
  yojson)
 (preprocess
  (pps lwt_ppx melange-json-native.ppx ppx_deriving_jsonschema)))

(rule
 (targets
  github_types_t.ml
  github_types_t.mli
  github_types_j.ml
  github_types_j.mli)
 (deps github_types.atd)
 (action
  (progn
   (run %{bin:atdgen} -j %{deps})
   (run %{bin:atdgen} -t %{deps}))))

(rule
 (targets
  review_types_t.ml
  review_types_t.mli
  review_types_j.ml
  review_types_j.mli)
 (deps review_types.atd)
 (action
  (progn
   (run %{bin:atdgen} -j %{deps})
   (run %{bin:atdgen} -t %{deps}))))

(rule
 (targets
  anthropic_types_t.ml
  anthropic_types_t.mli
  anthropic_types_j.ml
  anthropic_types_j.mli)
 (deps anthropic_types.atd)
 (action
  (progn
   (run %{bin:atdgen} -j %{deps})
   (run %{bin:atdgen} -t %{deps}))))
