(library
 (name reviewotron_lib)
 (libraries
  ocaml-ai-sdk.ai_core
  ocaml-ai-sdk.ai_provider
  ocaml-ai-sdk.ai_provider_anthropic
  base64
  containers
  curl
  devkit
  devkit.core
  extlib
  digestif
  lwt
  lwt.unix
  melange-json-native
  unix
  mirage-crypto-pk
  ppx_deriving_jsonschema.runtime
  ptime
  ptime.clock.os
  re2
  x509
  yojson)
 (preprocess
  (pps lwt_ppx melange-json-native.ppx ppx_deriving_jsonschema)))
