let generated_component = "__generated__"
let gen_component = "gen"

type skipped_file = {
  path : string;
  reason : string;
}

let marker_scan_limit = 30

(* Markers whose presence in a comment signals a generated file.

   "do not edit" is deliberately excluded: on its own it matches hand-authored
   files ("Do not edit without approval") as often as generated ones, and every
   generator that emits it also emits a "generated"-family marker below, so it
   adds no detection power while inviting false positives. *)
let generated_markers =
  [ "@generated"; "code generated"; "auto-generated"; "<auto-generated"; "automatically generated" ]

(* Leading punctuation for the comment syntaxes generated headers use. A marker
   is only trusted when it sits in a comment line, so prose in strings or docs
   that merely mentions the phrase does not trip the classifier. *)
let comment_prefixes = [ "//"; "#"; "(*"; "<!--"; "--"; ";"; "/*"; "*"; "%"; "\"" ]

let basename_suffixes =
  [
    ".min.js";
    ".min.css";
    ".map";
    ".grpc.pb.go";
    ".pb.go";
    ".pb.cc";
    ".pb.h";
    ".pb.swift";
    "_pb2.py";
    "_pb2.pyi";
    ".designer.cs";
    ".g.cs";
  ]

let path_components path = String.split_on_char '/' path

let directory_components path =
  match List.rev (path_components path) with
  | [] -> []
  | _basename :: dirs_rev -> List.rev dirs_rev

let component_generated_reason component =
  match component with
  | component when String.equal component generated_component ->
    Some (Printf.sprintf "%s path component" generated_component)
  | component when String.equal component gen_component -> Some (Printf.sprintf "%s path component" gen_component)
  | component when CCString.suffix ~suf:"_gen" component ->
    Some (Printf.sprintf "path component %S has _gen suffix" component)
  | _ -> None

let find_generated_directory_component path = List.find_map component_generated_reason (directory_components path)

let filename_stem basename =
  match String.rindex_opt basename '.' with
  | Some i when i > 0 -> String.sub basename 0 i
  | Some _ | None -> basename

let find_generated_filename_rule path =
  let basename = Filename.basename path in
  let stem = filename_stem basename in
  match () with
  | () when CCString.prefix ~pre:"generated_" stem ->
    Some (Printf.sprintf "filename stem %S has generated_ prefix" stem)
  | () when CCString.suffix ~suf:"_gen" stem -> Some (Printf.sprintf "filename stem %S has _gen suffix" stem)
  | () -> None

let find_basename_suffix path =
  List.find_opt (fun suffix -> CCString.suffix ~suf:suffix (Filename.basename path)) basename_suffixes

(* Only lines present in the new version of the file signal that it is
   generated. A Deletion carrying a marker means the marker is being removed,
   i.e. the file is being un-generated and should be reviewed. *)
let marker_scan_text = function
  | Diff_parser.Context text -> Some text
  | Diff_parser.Addition text -> Some text
  | Diff_parser.Deletion _ -> None

let first_diff_lines fd =
  fd.Diff_parser.hunks
  |> List.concat_map (fun h -> h.Diff_parser.lines)
  |> List.filter_map marker_scan_text
  |> CCList.take marker_scan_limit

(* A marker is only trusted inside a comment: the trimmed line must begin with
   comment punctuation. This keeps prose in strings or docs from matching. *)
let is_comment_line line =
  let trimmed = String.trim line in
  List.exists (fun prefix -> CCString.prefix ~pre:prefix trimmed) comment_prefixes

let line_marker line = List.find_opt (fun marker -> String_ext.contains_sub ~sub:marker line) generated_markers

let find_generated_marker fd =
  first_diff_lines fd
  |> List.find_map (fun line ->
    match is_comment_line line with
    | true -> line_marker (String.lowercase_ascii line)
    | false -> None)

(* Path-based rules classify on the file's current path only. A rename out of a
   generated location (e.g. __generated__/schema.ml -> src/schema.ml) makes the
   file hand-maintained and reviewable, so the stale old_path must not count. *)
let classify fd =
  let path = fd.Diff_parser.path in
  match find_generated_directory_component path with
  | Some reason -> Some { path; reason = Printf.sprintf "%s in %s" reason path }
  | None ->
  match find_generated_filename_rule path with
  | Some reason -> Some { path; reason = Printf.sprintf "%s in %s" reason path }
  | None ->
  match find_basename_suffix path with
  | Some suffix ->
    Some
      {
        path;
        reason = Printf.sprintf "basename %S matches generated artifact suffix %S" (Filename.basename path) suffix;
      }
  | None ->
  match find_generated_marker fd with
  | Some marker -> Some { path = fd.path; reason = Printf.sprintf "generated marker %S in first diff lines" marker }
  | None -> None

let filter diffs =
  let kept_rev, skipped_rev =
    List.fold_left
      (fun (kept, skipped) fd ->
        match classify fd with
        | Some skipped_file -> kept, skipped_file :: skipped
        | None -> fd :: kept, skipped)
      ([], []) diffs
  in
  List.rev kept_rev, List.rev skipped_rev

let describe_skipped = function
  | [] -> None
  | _ :: _ as skipped ->
    Some (skipped |> List.map (fun { path; reason } -> Printf.sprintf "%s (%s)" path reason) |> String.concat ", ")
