(executable
 (name reviewotron)
 (public_name reviewotron)
 (libraries
  reviewotron_lib
  cmdliner
  devkit
  devkit.core
  extlib
  lwt.unix
  unix
  mirage-crypto-rng.unix)
 (preprocess
  (pps lwt_ppx)))

(rule
 (targets build_info.ml)
 (action
  (with-stdout-to
   %{targets}
   (echo "let version = \"%{env:REVIEWOTRON_VERSION=dev}\""))))
